## Sorting

In [3]:
import numpy as np

In [34]:
unsorted = np.array(
   [5, 7, 1, 0, -1]
)

x = unsorted

print (type (np.sort(unsorted))) # numpy.ndarray
# print (np.sort(unsorted)) 

unsorted.sort()
print (unsorted)

print (np.may_share_memory(x, unsorted))


<class 'numpy.ndarray'>
[-1  0  1  5  7]
True


In [45]:
# Sorting a 2d array

unsorted_2d_array = np.array ([
   [4, 64, 0, 5, 100], 
   [54, 63, 10, 9, 51]
])


np.sort (unsorted_2d_array, axis=0)

array([[  4,  63,   0,   5,  51],
       [ 54,  64,  10,   9, 100]])

## Filter

In [ ]:
arr = np.array([41, 42, 43, 44])

# boolean index list 
# A boolean index list is a list of booleans corresponding to indexes in the array.


x = [True, False, True, False]

new_arr = arr[x]

print (new_arr)

[41 43]


In [67]:
arr = np.array ([2, 3, 4, 5, 6, 7, 8, 9])

filtered = []

for i in arr: 
   if i % 2 == 0: 
      filtered.append(True)
   else: 
      filtered.append(False)
   
even_nums = arr[filtered]


print (even_nums)

[2 4 6 8]


In [ ]:
# Shorthand 

filtered = arr % 2 == 0 
new_arr = arr[filtered]
print (new_arr)

# OR 


print (arr % 2 == 1) # returns a list of boolean: boolean index list
print (arr[arr % 2 == 1]) # odd numbers

[2 4 6 8]
[2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True]
[3 5 7 9]


In [ ]:
# Another simple example 
alphabets = np.array (['a', 'b', 'c'])

x = alphabets[[True, True, False]]

print (x)
# print (alphabets)

['a' 'b']
['a' 'b' 'c']
