## Join / Concatenation Operations / Axis

In [2]:
import numpy as np

In [ ]:
# concatenate two arrays
arr1 = np.array([1, 3, 4, 5, 6])
arr2 = np.array([3, 4, 5, 6, 7])

# Correct way: pass arrays as a tuple or list
arr = np.concatenate((arr1, arr2))  # Using tuple
# OR
# arr = np.concatenate([arr1, arr2])  # Using list

print(arr)
# Output: [1 3 4 5 6 3 4 5 6 7]

# You can also specify the axis explicitly (default is 0 for 1D arrays)
arr_axis0 = np.concatenate((arr1, arr2), axis=0)
print("With axis=0:", arr_axis0)

[1 3 4 5 6 3 4 5 6 7]
With axis=0: [1 3 4 5 6 3 4 5 6 7]


In [51]:
# 2D arrays concatenation along axis 0 and 1

arr1 = np.array([
   [1, 2, 3], 
   [4, 5, 6]
])

arr2 = np.array([
   [7, 8, 9], 
   [10, 11, 12]
])

print (np.concatenate((arr1, arr2), axis=1)) # concatenate the rows 
print (np.concatenate((arr1, arr2), axis=0)) # concatenate the columns 
# print (arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [54]:
# Axes 

np_array_2d = np.arange(0, 6).reshape([2, 3])

# print (np_array_2d)

# Sum along x-axis

"""
   [
      [0 , 1 , 2], 
      [3 , 4 , 5]
   ]
"""


print(np.sum(np_array_2d, axis=0))  # Sum along columns
print(np.sum(np_array_2d, axis=1))  # Sum along rows

[3 5 7]
[ 3 12]


In [ ]:
# Example:

np_array_1s = np.array([
   [1,1,1],
   [1,1,1]
])


np_array_9s = np.array([
   [9,9,9],
   [9,9,9]
])

print (np.concatenate ([np_array_1s, np_array_9s] , axis=0))
print (np.concatenate ((np_array_1s, np_array_9s) , axis=1))

In [ ]:
zeros = np.zeros(5)
ones = np.ones(5)

print (np.concatenate([zeros, ones], axis=0))
# The issue is that in 1-d arrays, axis 0 doesn't point “downward” like it does in a 2-dimensional array.

In [ ]:
# # Stacking: Horizontal, Vertical, Height/Depth

# # stacking is done along a new axis 

arr1 = np.array ([1, 2, 3])
arr2 = np.array ([4, 5, 6])

# arr = np.stack ((arr1, arr2), axis=0)

arr = np.hstack((arr1, arr2))
# arr = np.vstack((arr1, arr2))
# arr = np.dstack((arr1, arr2))
print (arr)


[[[1 4]
  [2 5]
  [3 6]]]
